version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  api:
    depends_on:
      - mysqldb
    build: ./ApiService
    restart: unless-stopped
    env_file: ./.env
    # ports:
    #   - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  account:
    depends_on:
      - mysqldb
    build: ./AccountService
    restart: unless-stopped
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
  nginx:
    depends_on:
      - account
      - api
    restart: always
    image: nginx:1.21.4-alpine
    ports:
      - "8080:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
volumes:
  db:
